env:
  browser: true
extends:
  - 'airbnb-base'
  - 'plugin:meteor/recommended'
parser: 'babel-eslint'
parserOptions:
  allowImportExportEverywhere: true
  ecmaVersion: 7
plugins:
  - meteor
rules:
  func-names:
    - error
    - never
  import/no-extraneous-dependencies: 0
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
settings:
  import/resolver: meteor
